# NumPy

NumPy is the fundamental package for scientific computing with Python. Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. It contains among other things:
* A powerful N-dimensional array object.
* Sophisticated (broadcasting) functions.
* Useful linear algebra, Fourier transform, and random number capabilities.

In [1]:
# importing numpy 
import numpy as np

Basic important techniques for numpy.
* Boadcasting
* Indexing

## Create Array

This section contain basic of array creation. To know more about numpy data type follow this [link](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html). You can also find more detail about ndarray on this [link](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html).

In [2]:
# create a 1D numpy array using np.array(list)
data = [1.0, 2.0, 3.0, 4.0, 5.0]
array = np.array(data, float)
print(array)

[ 1.  2.  3.  4.  5.]


In [3]:
# create a 2D numpy array
data_2d = [[1, 2, 3], [4, 5, 6],[7, 8, 9]]
array_2d = np.array(data_2d, float)
print(array_2d)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [4]:
array_2d.shape

(3, 3)

## Indexing and Slicing
Numpy follows Python's rules "Includes the first" and "Excludes the last" :

In [5]:
# access the value by index
print(array[1])
print(array_2d[1])

2.0
[ 4.  5.  6.]


In [6]:
# access from first to third
array[1: 3]

array([ 2.,  3.])

In [7]:
# access from second to last
array[1:]

array([ 2.,  3.,  4.,  5.])

In [8]:
# row 1, all columns
array_2d[1,:2]

array([ 4.,  5.])

## Matrix Arithmetic

In [9]:
# element-wise addition
array_2d + array_2d

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.],
       [ 14.,  16.,  18.]])

In [10]:
# element-wise subtractaction
array_2d - array_2d

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [11]:
# element-wise multiplication
array_2d * array_2d

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.],
       [ 49.,  64.,  81.]])

## Mean and Dot

In [12]:
# method to find mean
np.mean(array_2d)

5.0

In [13]:
# method to find dot product
np.dot(array_2d, array_2d)

array([[  30.,   36.,   42.],
       [  66.,   81.,   96.],
       [ 102.,  126.,  150.]])

## Solving Multiple Linear Equations

In [14]:
# coefficient matrix 
A = np.array([[1, 2, -1], [2, 1, 1], [1, 2, 1]])

# numbers on the right without variables
b = np.array([4, -2, 2])

# solve using np.linagl.solve()
np.linalg.solve(A, b)

array([-1.66666667,  2.33333333, -1.        ])

## Miscellaneous

In [3]:
np.arange(start=0,stop=10,step=2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(shape=(1,5),dtype=int)

array([[0, 0, 0, 0, 0]])

In [9]:
np.ones(shape=(1,3),dtype=float)

array([[1., 1., 1.]])

In [14]:
np.linspace(start=0,stop=10,num=3)

array([ 0.,  5., 10.])

In [19]:
np.random.randint(low=5,high=15,size=(1,3))

array([[6, 9, 6]])

In [22]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [23]:
print(arr)

[95 11 81 70 63 87 75  9 77 40]


In [24]:
arr.max()

95

In [25]:
arr.min()

9

In [26]:
arr.mean()

60.8

In [27]:
arr.argmax()

0

In [28]:
arr.argmin()

7

In [29]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [31]:
mat = np.arange(0,25).reshape(5,5)

In [33]:
mat[4,3]

23

In [36]:
mat[:,0]

array([ 0,  5, 10, 15, 20])

In [37]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [40]:
filter_mal = mat > 3

In [41]:
mat[filter_mal]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])