# Numpy 

NumPy is the fundamental package for scientific computing with Python. Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. It contains among other things:
* A powerful N-dimensional array object.
* Sophisticated (broadcasting) functions.
* Useful linear algebra, Fourier transform, and random number capabilities.

In [1]:
# importing numpy 
import numpy as np

Basic important techniques for numpy.
* Boadcasting
* Indexing

## Create Array

In [13]:
# create a 1D numpy array using np.array(list)
data = [1.0, 2.0, 3.0, 4.0, 5.0]
array = np.array(data, float)
print(array)

[ 1.  2.  3.  4.  5.]


In [21]:
# create a 2D numpy array
data_2d = [[1, 2, 3], [4, 5, 6],[7, 8, 9]]
array_2d = np.array(data_2d, float)
print(array_2d)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [22]:
array_2d.shape

(3, 3)

## Indexing and Slicing
Numpy follows Python's rules "Includes the first" and "Excludes the last" :

In [23]:
# access the value by index
print(array[1])
print(array_2d[1])

2.0
[ 4.  5.  6.]


In [24]:
# access from first to third
array[1: 3]

array([ 2.,  3.])

In [25]:
# access from second to last
array[1:]

array([ 2.,  3.,  4.,  5.])

In [28]:
# row 1, all columns
array_2d[1,:2]

array([ 4.,  5.])

## Matrix Arithmetic

In [29]:
# element-wise addition
array_2d + array_2d

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.],
       [ 14.,  16.,  18.]])

In [30]:
# element-wise subtractaction
array_2d - array_2d

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [31]:
# element-wise multiplication
array_2d * array_2d

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.],
       [ 49.,  64.,  81.]])

## Mean and Dot

In [32]:
np.mean(array_2d)

5.0

In [33]:
np.dot(array_2d, array_2d)

array([[  30.,   36.,   42.],
       [  66.,   81.,   96.],
       [ 102.,  126.,  150.]])

## Solving Multiple Linear Equations

In [34]:
# coefficient matrix 
A = np.array([[1, 2, -1], [2, 1, 1], [1, 2, 1]])

# numbers on the right without variables
b = np.array([4, -2, 2])

# solve using np.linagl.solve()
np.linalg.solve(A, b)

array([-1.66666667,  2.33333333, -1.        ])